apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backend
  - frontend
namespace: study-app
namePrefix: prod-
images:
  - name: backend
    newName: ghcr.io/mischavandenburg/study-app-b
    newTag: backend-v0.13.1
  - name: frontend
    newName: ghcr.io/mischavandenburg/study-app-f
    newTag: frontend-v0.7.1
