apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backend
  - frontend
namespace: study-app
namePrefix: dev-
images:
  - name: backend
    newName: ghcr.io/mischavandenburg/study-app-b
    newTag: ghcr.io/mischavandenburg/study-app-b:backend-v0.12.5
  - name: frontend
    newName: ghcr.io/mischavandenburg/study-app-f
    newTag: frontend-v0.4.2
